[mysql]
  dbname  = "mydb"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = ""
  sslmode = "false"
  blacklist = ["schema_migrations"]
  whitelist = ["user"]

[go]
  package = "mypackage"
  output  = "stdout"
