[mysql]
  dbname  = "mydb"
  host    = "localhost"
  port    = 3306
  user    = "root"
  pass    = ""
  sslmode = "false"
  blacklist = ["schema_migrations"]
  whitelist = ["mytable"]

[go]
  package = "legacy"
  output  = ""
  imports = ["database/sql", "time", "github.com/jmoiron/sqlx"]

[type]
  "types.Decimal"     = "float64"
  "types.JSON"        = "string"
  "types.NullDecimal" = "sql.NullFloat64"
  "null.String"       = "sql.NullString"
  "null.Float32"      = "sql.NullFloat32"
  "null.Float64"      = "sql.NullFloat64"
  "null.Int"          = "sql.NullInt32"
  "null.Int8"         = "sql.NullInt32"
  "null.Int16"        = "sql.NullInt32"
  "null.Int32"        = "sql.NullInt32"
  "null.Int64"        = "sql.NullInt64"
  "null.Uint"         = "sql.NullInt32"
  "null.Uint8"        = "sql.NullInt32"
  "null.Uint16"       = "sql.NullInt32"
  "null.Uint32"       = "sql.NullInt32"
  "null.Uint64"       = "sql.NullInt64"
  "null.Bool"         = "sql.NullBool"
  "null.Time"         = "sql.NullTime"
  "null.Bytes"        = "sql.NullString"
  "null.JSON"         = "sql.NullString"
